name: stay_connected_flutter
description: Flutter migration of Stay Connected app
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.2.0
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  intl: ^0.19.0
  flutter_slidable: ^3.1.0
  modal_bottom_sheet: ^3.0.0
  share_plus: ^10.0.0
  url_launcher: ^6.3.0
  package_info_plus: ^8.0.0
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.0
  firebase_analytics: ^11.3.0

  flutter_animate: ^4.5.0
  freezed_annotation: ^2.4.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flex_color_scheme: ^7.3.1
  device_calendar: ^4.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
